title: Yijia Liu
logo: "/images/logo.png"
description: > # newlines will be ignored in this theme, using <br> instead
  Transportation Planner (ArcGIS, VISUM, VISSIM, TransCAD)
  <br>
  Spatial Data Analyst (Python / R)
  <br><br>
  Master of City Planning 
  <br>
  *University of Pennsylvania*
  <br>
  Bachelor of Arts in Urban Studies (The University of Hong Kong)
  <br><br>
  <a href="www.linkedin.com/yijia-liu">View My LinkedIn Profile</a>
  
theme: jekyll-theme-minimal
google_analytics: 
